<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gsc</string>
		<string>csc</string>
		<string>gsh</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*/\*|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>^\s*\*/|^\s*\}</string>
	<key>name</key>
	<string>GSC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.source.gsc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.source.gsc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.source.gsc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.source.gsc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>#/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.source.gsc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.devblock.source.gsc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#documentation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#supports</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>comment</key>
					<string>Block Comment</string>
					<key>end</key>
					<string>\*/\n?</string>
					<key>name</key>
					<string>comment.block.gsc</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Line Comment</string>
					<key>match</key>
					<string>//.*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.gsc</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.source.gsc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.gsc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@"([^"]|"")*"</string>
					<key>name</key>
					<string>string.quoted.double.literal.source.gsc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.source.gsc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.source.gsc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.source.gsc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.source.gsc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(undefined|false|true|self|world|classes|level|game|anim|vararg)\b</string>
					<key>name</key>
					<string>constant.language.source.gsc</string>
				</dict>
			</array>
		</dict>
		<key>documentation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/@</string>
					<key>comment</key>
					<string>Block Comment</string>
					<key>end</key>
					<string>@/</string>
					<key>name</key>
					<string>comment.block.documentation.gsc</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|while|for|foreach|in|do|return|continue|break|switch|case|default)\b</string>
					<key>name</key>
					<string>keyword.control.source.gsc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(size|assert|assertmsg|notify|endon)\b</string>
					<key>name</key>
					<string>keyword.operator.source.gsc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(class|function|var|wait|thread|waittill|waittillmatch|waittillframeend|isdefined|constructor|destructor|autoexec|private|const)\b</string>
					<key>name</key>
					<string>keyword.other.source.gsc</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.preprocessor.source.gsc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(define)\b\s*(\S*)</string>
					<key>name</key>
					<string>keyword.preprocessor.source.gsc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.source.gsc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(if|ifdef|ifndef|else|elif|endif|define|insert|using|precache|using_animtree)\b</string>
					<key>name</key>
					<string>keyword.preprocessor.source.gsc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.namespace.identifier</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(namespace)\b</string>
					<key>name</key>
					<string>keyword.preprocessor.source.gsc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gsc</string>
	<key>uuid</key>
	<string>81223a8d-3586-41df-8606-255ca394f9d7</string>
</dict>
</plist>
